# See https://github.com/netlify/netlify-cms/blob/master/example/config.yml
backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# display_url: https://gatsbro.netlify.com # This url will display in the top-right of the CMS
media_library:
  name: uploadcare
  config:
    publicKey: a73a170cb5cdef662983
    multiple: false
    tabs: 'file camera url facebook gdrive'
    effects: 'crop,rotate,enhance,grayscale'
    imageShrink: '2000x2000'
    previewStep: true
    clearable: true

collections: # A list of collections the CMS should be able to edit

  - name: 'pages'
    label: 'Pages'
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: true
    files:

      - file: 'content/pages/home.md'
        label: 'Home Page'
        name: 'home-page'
        fields:
          - {
              label: Template,
              name: template,
              widget: hidden,
              default: HomePage,
            }
          - { label: Slug, name: slug, widget: hidden, default: 'home' }
          - { label: Title, name: title, widget: string }
          - { label: Listed Mix, name: listedmix, widget: string }
          - { label: Listed Mix Link, name: listedmixlk, widget: string }
          - { label: Featured Image 1, name: featuredImage, widget: image }
          - { label: Featured Image 2, name: featuredImage2, widget: image }
          - { label: Featured Image 3, name: featuredImage3, widget: image }
          - { label: Featured Image 4, name: featuredImage4, widget: image }
          - { label: Featured Image 5, name: featuredImage5, widget: image }
          - { label: Artist Links, name: subtitle, widget: markdown }
          - label: 'Meta'
            required: false
            name: 'meta'
            widget: 'object'
            fields:
              - { label: Title, name: title, widget: string, required: false }
              - {
                  label: Description,
                  name: description,
                  widget: text,
                  required: false,
                }
              - {
                  label: Canonical Link,
                  name: canonicalLink,
                  widget: string,
                  required: false,
                }
              - {
                  label: Noindex,
                  name: noindex,
                  widget: boolean,
                  required: false,
                }

      - file: 'content/pages/productions.md'
        label: 'Productions Page'
        name: 'productions-page'
        fields:
          - {
              label: Template,
              name: template,
              widget: hidden,
              default: ProductionsPage,
            }
          - { label: Slug, name: slug, widget: hidden, default: 'componets' }
          - { label: Title, name: title, widget: string }
          - { label: Featured Images, name: featuredImage, widget: image }
          - { label: Section 1, name: section1, widget: markdown }
          - { label: Section 2, name: section2, widget: markdown }
          - { name: video, label: video, widget: file }
          - { name: videoPoster, label: videoPoster, widget: image }
          - { label: videoTitle, name: videoTitle, widget: string }
          - label: 'Gallery'
            name: 'gallery'
            widget: 'list'
            fields:
              - { name: image, label: Image, widget: image }
              - { name: alt, label: Alt, widget: string }
              - { name: title, label: Title, widget: string, required: false }
          - label: 'Meta'
            required: false
            name: 'meta'
            widget: 'object'
            fields:
              - { label: Title, name: title, widget: string, required: false }
              - {
                  label: Description,
                  name: description,
                  widget: text,
                  required: false,
                }
              - {
                  label: Canonical Link,
                  name: canonicalLink,
                  widget: string,
                  required: false,
                }
              - {
                  label: Noindex,
                  name: noindex,
                  widget: boolean,
                  required: false,
                }
      
      - file: 'content/pages/contact.md'
        label: 'Contact Page'
        name: 'contact-page'
        fields:
          - {
              label: Template,
              name: template,
              widget: hidden,
              default: ContactPage,
            }
          - { label: Slug, name: slug, widget: hidden, default: 'contact' }
          - { label: Title, name: title, widget: string }
          - {
              label: Featured Image,
              name: featuredImage,
              widget: image,
              options:
                { media_library: { config: { imageShrink: 2600x2600 } } },
            }
          - { label: Subtitle, name: subtitle, widget: markdown }
          - { label: Body, name: body, widget: markdown }
          - { label: Address, name: address, widget: text }
          - { label: Phone, name: phone, widget: string }
          - { label: Email Address, name: email, widget: string }
          - name: locations
            label: locations
            widget: list
            fields:
              - {
                  name: mapLink,
                  label: mapLink,
                  widget: string,
                  required: false,
                  default: '',
                }
              - {
                  name: lat,
                  label: latitude,
                  widget: string,
                  required: false,
                  delete: false,
                  default: '',
                }
              - {
                  name: lng,
                  label: longitude,
                  widget: string,
                  required: false,
                  delete: false,
                  default: '',
                }
          - label: 'Meta'
            required: false
            name: 'meta'
            widget: 'object'
            fields:
              - { label: Title, name: title, widget: string, required: false }
              - {
                  label: Description,
                  name: description,
                  widget: text,
                  required: false,
                }
              - {
                  label: Canonical Link,
                  name: canonicalLink,
                  widget: string,
                  required: false,
                }
              - {
                  label: Noindex,
                  name: noindex,
                  widget: boolean,
                  required: false,
                }

      - file: 'content/pages/enter.md'
        label: 'Enter Page'
        name: 'enter-page'
        fields:
          - {
              label: Template,
              name: template,
              widget: hidden,
              default: EnterPage,
            }
          - { label: Slug, name: slug, widget: hidden, default: '' }
          - { label: Title, name: title, widget: string }
          - label: 'Meta'
            required: false
            name: 'meta'
            widget: 'object'
            fields:
              - { label: Title, name: title, widget: string, required: false }
              - {
                  label: Description,
                  name: description,
                  widget: text,
                  required: false,
                }

      - file: 'content/pages/artists.md'
        label: 'Artist Page'
        name: 'blog-page2'
        fields:
          - {
              label: Template,
              name: template,
              widget: hidden,
              default: ArtistPage,
            }
          - { label: Slug, name: slug, widget: hidden, default: 'blog' }
          - { label: Title, name: title, widget: string }
          - label: 'Meta'
            required: false
            name: 'meta'
            widget: 'object'
            fields:
              - { label: Title, name: title, widget: string, required: false }
              - {
                  label: Description,
                  name: description,
                  widget: text,
                  required: false,
                }
              - {
                  label: Canonical Link,
                  name: canonicalLink,
                  widget: string,
                  required: false,
                }
              - {
                  label: Noindex,
                  name: noindex,
                  widget: boolean,
                  required: false,
                }

      - file: 'content/pages/news.md'
        label: 'News Page'
        name: 'blog-page'
        fields:
          - {
              label: Template,
              name: template,
              widget: hidden,
              default: BlogIndex,
            }
          - { label: Slug, name: slug, widget: hidden, default: 'news' }
          - { label: Title, name: title, widget: string }
          - { label: Featured Image, name: featuredImage, widget: image }
          - label: 'Meta'
            required: false
            name: 'meta'
            widget: 'object'
            fields:
              - { label: Title, name: title, widget: string, required: false }
              - {
                  label: Description,
                  name: description,
                  widget: text,
                  required: false,
                }
              - {
                  label: Canonical Link,
                  name: canonicalLink,
                  widget: string,
                  required: false,
                }
              - {
                  label: Noindex,
                  name: noindex,
                  widget: boolean,
                  required: false,
                }


  - name: posts
    label: News
    editor:
      preview: true
    folder: content/posts
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: Page Link, name: url, widget: string}
      - { label: Template, name: template, widget: hidden, default: SinglePost }
      - { label: Title, name: title, widget: string }

      - label: 'Status'
        name: 'status'
        widget: 'select'
        options: ['Published', 'Featured', 'Draft', 'Button']
        default: 'Published'
      - { label: Date / Order, name: date, widget: date }
      - {
          label: Featured Image,
          name: featuredImage,
          widget: image,
          required: false,
        }
      - { label: Content, name: body, widget: markdown }
      - label: 'Meta'
        required: false
        name: 'meta'
        widget: 'object'
        fields:
          - { label: Title, name: title, widget: string, required: false }
          - {
              label: Description,
              name: description,
              widget: text,
              required: false,
            }
          - {
              label: Canonical Link,
              name: canonicalLink,
              widget: string,
              required: false,
            }
          - { label: Noindex, name: noindex, widget: boolean, required: false }

  - name: artists
    label: Artists
    editor:
      preview: true
    folder: content/artists
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have

      - { label: Template, name: template, widget: hidden, default: ArtistPost }
      - { label: Artist Name, name: title, widget: string }
      - {
          label: Featured Image,
          name: featuredImage,
          widget: image,
        }
      - { label: Bio, name: body, widget: markdown }
      - { label: Upcoming Shows, name: upcomingshows, required: false, widget: text }

      - {label: "Facebook Link", name: fblk, required: false, widget: string}
      - {label: "Instagram Link", name: instalk, required: false, widget: string}
      - {label: "Resident Advisor Link", name: ralk, required: false, widget: string}
      - {label: "Twitter Link", name: twitterlk, required: false, widget: string}
      - {label: "Spotify Link", name: spotifylk, required: false, widget: string}
      - {label: "SoundCloud Link", name: sclk, required: false, widget: string}
      - {label: Presskit, name: presskit, required: false, widget: string}
      - {label: Soundcloud Widget, name: scwidg, required: false, widget: string}
      - {label: Youtube Widget, name: videowidg, required: false, widget: string}
      - {label: Spotify Widget, name: spotifywidg, required: false, widget: string}

      - label: 'Status'
        name: 'status'
        widget: 'select'
        options: ['Published', 'Featured', 'Draft']
        default: 'Published'
      - { label: Date / Order, name: date, widget: date }

      - label: 'Meta'
        required: false
        name: 'meta'
        widget: 'object'
        fields:
          - { label: Title, name: title, widget: string, required: false }
          - {
              label: Description,
              name: description,
              widget: text,
              required: false,
            }
          - {
              label: Canonical Link,
              name: canonicalLink,
              widget: string,
              required: false,
            }
          - { label: Noindex, name: noindex, widget: boolean, required: false }
     
  - name: 'settings'
    label: 'Settings'
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: false
    files:
      - file: 'content/settings/global.yml'
        label: 'Global Settings'
        name: 'global-settings'
        fields:
          - { label: Site Title, name: siteTitle, widget: string }
          - { label: Site Url, name: siteUrl, widget: string, required: false }
          - {
              label: Site Description,
              name: siteDescription,
              widget: text,
              required: false,
            }
          - label: Social Media Card
            name: socialMediaCard
            widget: object
            fields:
              - { label: Image, name: image, widget: image, required: false }
          - {
              label: Google Analytics Tracking Id,
              name: googleTrackingId,
              widget: string,
              required: false,
            }